export enum Permission{
  CREATE_USER,
  DELETE_USER,
  FIND_USER,
  LIST_USERS,
  CREATE_DEPARTMENT,
  DELETE_DEPARTMENT,
  FIND_DEPARTMENT,
  UPDATE_DEPARTMENT,
  ASSIGN_USER_TO_DEPARTMENT,
  LIST_DEPARTMENTS,
  LIST_DEPARTMENT_USERS,
  UPDATE_OWN_DEPARTMENT,
  MANAGE_OWN_TASKS
}